# Generated by Django 2.2.17 on 2021-01-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='some_value'),
        ),
    ]
